openapi: 3.0.0
info:
  title: Snake API
  version: 1.0.0
paths:
  /scores:
    get:
      summary: Lista os scores
      responses:
        "200":
          description: Lista de scores
    post:
      summary: Cria um novo score
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                pontos:
                  type: integer
      responses:
        "201":
          description: Score criado
  /scores/{id}:
    delete:
      summary: Deleta um score
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Score deletado
